# PA2 Numerical Python

### NORMALIZATION PROBLEM

In [5]:
#importing numpy as np
import numpy as np

In [7]:
#creating a random 5x5 array
X = np.random.rand(5,5)

In [17]:
print("Original array X:")
print(X)

Original array X:
[[0.10757796 0.29269355 0.73954088 0.49432014 0.25602148]
 [0.66124186 0.17117618 0.47778438 0.93699211 0.30398111]
 [0.63357976 0.01985227 0.67968863 0.5756826  0.05940622]
 [0.69273729 0.4061485  0.64454351 0.59346708 0.47588203]
 [0.22021457 0.63532282 0.94479499 0.79000175 0.40865083]]


In [19]:
#calculating for the mean and standard deviation
mean_X = X.mean()
std_X = X.std()

In [23]:
#Normalizing the array
X_normalized = (X - mean_X) / std_X

In [27]:
#output of normalized array
print("Normalized array:")
print(X_normalized)

Normalized array:
[[-1.49853771 -0.77097013  0.98529258  0.02149128 -0.91510391]
 [ 0.67755067 -1.24857494 -0.04349993  1.76134344 -0.72660619]
 [ 0.56882919 -1.84332966  0.75005279  0.34127354 -1.68786911]
 [ 0.80133851 -0.32505342  0.61192046  0.41117261 -0.05097681]
 [-1.05583734  0.57567999  1.79201142  1.18362107 -0.31521839]]


In [39]:
#saving the normalized array in a file
np.save('X_normalized.npy', X_normalized)

In [46]:
print("Normalized array has been saved to 'X_normalized.npy'")

Normalized array has been saved to 'X_normalized.npy'


In [48]:
#loading the saved file
np.load('X_normalized.npy')

array([[-1.49853771, -0.77097013,  0.98529258,  0.02149128, -0.91510391],
       [ 0.67755067, -1.24857494, -0.04349993,  1.76134344, -0.72660619],
       [ 0.56882919, -1.84332966,  0.75005279,  0.34127354, -1.68786911],
       [ 0.80133851, -0.32505342,  0.61192046,  0.41117261, -0.05097681],
       [-1.05583734,  0.57567999,  1.79201142,  1.18362107, -0.31521839]])

## DIVISIBLE BY 3 PROBLEM

In [50]:
#importing numpy as np
import numpy as np

In [52]:
# Creating the 10x10 array where each element is the square of integers from 1 to 100
A = np.array([i**2 for i in range(1, 101)]).reshape(10, 10)

In [54]:
# Printing the array
print("Array A (squares of integers from 1 to 100):")
print(A)

Array A (squares of integers from 1 to 100):
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [66]:
#function to find which elements are divisible by 3
divisible_by_3 = A[A % 3 == 0]

In [68]:
#printing the elements that are divisible by 3
print("Elements Divisible by 3: ")
print(divisible_by_3)

Elements Divisible by 3: 
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [70]:
# Save the result to a file
np.save('div_by_3.npy', div_by_3)

In [74]:
#loading the saved file
np.load('div_by_3.npy')

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])